//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabajoDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donacion
    {
        public int idDonacion { get; set; }
        public Nullable<int> idDonador { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<System.DateTime> fechaEntrega { get; set; }
        public Nullable<int> idPersona { get; set; }
    
        public virtual Donador Donador { get; set; }
        public virtual personaPobreza personaPobreza { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
